CREATE TABLE "orders" (
  "id" BIGINT NOT NULL,
  "product_id" BIGINT NOT NULL,
  "quantity" INT NOT NULL
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL
);

CREATE TABLE "racks" (
  "name" varchar NOT NULL,
  "product_id" BIGINT NOT NULL,
  "is_main" bool NOT NULL
);

CREATE INDEX ON "orders" ("id");

CREATE INDEX ON "products" ("id");

CREATE INDEX ON "racks" ("product_id");

ALTER TABLE "orders" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "racks" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");
