// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import ()

type Order struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
	Quantity  int64 `json:"quantity"`
}

type Product struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Rack struct {
	Name      string `json:"name"`
	ProductID int64  `json:"product_id"`
	IsMain    bool   `json:"is_main"`
}
