// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: orders.sql

package db

import (
	"context"
)

const getOrder = `-- name: GetOrder :many
SELECT id, product_id, quantity FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrder, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.ID, &i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
