// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: products.sql

package db

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, name FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
