// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	GetMainRack(ctx context.Context, productID int64) (Rack, error)
	GetOrder(ctx context.Context, id int64) ([]Order, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetSecondaryRacks(ctx context.Context, productID int64) ([]Rack, error)
}

var _ Querier = (*Queries)(nil)
